version: '3'
services:
  nba-service:
    build: ./
    environment:
      APPLICATION_PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_EXPIRE_TIME: 10
    depends_on:
      - redis
    ports:
      - 3000:3000

  redis:
    image: redis:latest
    volumes:
      - redis:/data
    ports:
      - 6379:6379

volumes:
  redis:
    driver: local
